import {
  IsectionOneList,
  IsectionTwoMenuList,
  SectionTwoHeaderItemsList,
} from "../../../interfaces_types/common/header";

export const sectionOneNavigation: IsectionOneList = {
  "Find a store": "",
  Help: "",
  Login: "",
  "Sign Up": "",
};

export const sectionTwoMenu: IsectionTwoMenuList = {
  Search: {
    svgPath:
      "M13.962 16.296a6.716 6.716 0 01-3.462.954 6.728 6.728 0 01-4.773-1.977A6.728 6.728 0 013.75 10.5c0-1.864.755-3.551 1.977-4.773A6.728 6.728 0 0110.5 3.75c1.864 0 3.551.755 4.773 1.977A6.728 6.728 0 0117.25 10.5a6.726 6.726 0 01-.921 3.407c-.517.882-.434 1.988.289 2.711l3.853 3.853",
    isCommon: true,
    onSmall: true,
    path: "#",
  },
  User: {
    svgPath:
      "M3.75 21v-3a3.75 3.75 0 013.75-3.75h9A3.75 3.75 0 0120.25 18v3M12 3.75a3.75 3.75 0 100 7.5 3.75 3.75 0 000-7.5z",
    path: "#",
    isCommon: false,
    onSmall: true,
  },
  Favourites: {
    svgPath:
      "M16.794 3.75c1.324 0 2.568.516 3.504 1.451a4.96 4.96 0 010 7.008L12 20.508l-8.299-8.299a4.96 4.96 0 010-7.007A4.923 4.923 0 017.205 3.75c1.324 0 2.568.516 3.504 1.451l.76.76.531.531.53-.531.76-.76a4.926 4.926 0 013.504-1.451",
    isCommon: false,
    onSmall: false,
    path: "#",
  },
  Cart: {
    svgPath:
      "M8.25 8.25V6a2.25 2.25 0 012.25-2.25h3a2.25 2.25 0 110 4.5H3.75v8.25a3.75 3.75 0 003.75 3.75h9a3.75 3.75 0 003.75-3.75V8.25H17.5",
    isCommon: true,
    onSmall: true,
    path: "#",
  },
  Options: {
    svgPath: "M21 5.25H3M21 12H3m18 6.75H3",
    isCommon: false,
    onSmall: true,
    path: "#",
  },
};

export const SectionTwoHeaderItems: SectionTwoHeaderItemsList = {
  "new & featured": {
    "new & featured": {
      "new arrivals": "#",
      "latest shoes": "#",
      "latest clothing": "#",
      "SNKRS launch calendar": "#",
      "get 'em in SNKRS": "#",
      "customize with Nke by you": "#",
      bestsellers: "#",
      "member exclusive": "#",
      "top kicks usder Rs.8000": "#",
    },
    "shop icons": {
      "air force 1": "#",
      "air jordan 1": "#",
      "air max": "#",
      dunk: "#",
      cortez: "#",
      blazer: "#",
      pegasus: "#",
    },
    "new for men": {
      shoes: "#",
      clothing: "#",
      accessories: "#",
      "shop all new": "#",
    },
    "new for women": {
      shoes: "#",
      clothing: "#",
      accessories: "#",
      "shop all new": "#",
    },
    "new for kids": {
      shoes: "#",
      clothing: "#",
      accessories: "#",
      "shop all new": "#",
    },
  },
  men: {
    featured: {
      "new releases": "#",
      bestsellers: "#",
      "member exclusive": "#",
      jordan: "#",
      "lifestyle running": "#",
      "customise with nike by you": "#",
      sale: "#",
      "running shoe finder": "#",
      "sustainable materials": "#",
    },
    shoes: {
      "all shoes": "#",
      "newest sneakers": "#",
      jordan: "#",
      lifestyle: "#",
      running: "#",
      "gym and training": "#",
      basketball: "#",
      football: "#",
      "sandals and slides": "#",
      "last sizes available": "#",
      "customise with nike by you": "#",
      "top picks under ₹ 8,000.00": "#",
    },
    clothing: {
      "all clothing": "#",
      "tops and t-shirts": "#",
      shorts: "#",
      "pants and leggings": "#",
      "hoodies and sweatshirts": "#",
      "jackets and gilets": "#",
      "jerseys and kits": "#",
      jordan: "#",
    },
    "shop by sport": {
      running: "#",
      basketball: "#",
      football: "#",
      golf: "#",
      tennis: "#",
      "gym and training": "#",
      yoga: "#",
      skateboarding: "#",
    },
    "accessories and equipment": {
      "all accessories and equipment": "#",
      "bags and backpacks": "#",
      socks: "#",
      "hats and headwear": "#",
    },
    "shop by brand": {
      "nike sportswear": "#",
      nikelab: "#",
      "nike by you": "#",
      jordan: "#",
      ACG: "#",
      NBA: "#",
      "nike sb": "#",
    },
    jordan: {
      "all jordan": "#",
      "new jordan": "#",
      "jordan shoes": "#",
      "jordan clothing": "#",
      "jordan basketball": "#",
      "jordan lifestyle": "#",
    },
  },
  women: {
    featured: {
      "new releases": "#",
      bestsellers: "#",
      "member exclusive": "#",
      "lifestyle running": "#",
      "bra and legging duos": "#",
      "customise with nike by you": "#",
      sale: "#",
      "find your feel - nike leggings": "#",
      "running shoe finder": "#",
      "sustainable materials": "#",
    },
    shoes: {
      "all shoes": "#",
      "newest sneakers": "#",
      "platform sneakers": "#",
      lifestyle: "#",
      jordan: "#",
      running: "#",
      "gym and training": "#",
      "sandals and slides": "#",
      basketball: "#",
      football: "#",
      "last sizes available": "#",
      "customise with nike by you": "#",
      "top picks under ₹ 8,000.00": "#",
    },
    clothing: {
      "all clothing": "#",
      "performance essentials": "#",
      "tops and t-shirts": "#",
      "sports bras": "#",
      "pants and leggings": "#",
      shorts: "#",
      "hoodies and sweatshirts": "#",
      "jackets and gilets": "#",
      "skirts and dresses": "#",
      "modest wear": "#",
      "nike maternity": "#",
      "plus size": "#",
    },
    "accessories and equipment": {
      "all accessories and equipment": "#",
      "bags and backpacks": "#",
      socks: "#",
      "hats and headwear": "#",
    },
    "shop by sport": {
      yoga: "#",
      running: "#",
      "gym and training": "#",
      basketball: "#",
      tennis: "#",
      golf: "#",
      football: "#",
      skateboarding: "#",
    },
    "shop by brand": {
      "nike sportswear": "#",
      nikelab: "#",
      "nike by you": "#",
      jordan: "#",
      acg: "#",
      nba: "#",
      "nike sb": "#",
    },
  },
  kids: {
    featured: {
      "new releases": "#",
      "newest sneakers": "#",
      "easy on & off": "#",
      bestsellers: "#",
      "member exclusive": "#",
      jordan: "#",
      "last sizes available": "#",
      "bags and backpacks": "#",
      sale: "#",
    },
    "kids by age": {
      "older kids (7 - 14 years)": "#",
      "younger kids (4 - 7 years)": "#",
      "babies & toddlers (0 - 4 years)": "#",
    },
    "boys shoes": {
      "all shoes": "#",
      "older boys (7 - 14 years)": "#",
      "younger boys (4 - 7 years)": "#",
      "babies and toddlers (0 - 4 years)": "#",
      lifestyle: "#",
      jordan: "#",
      running: "#",
      basketball: "#",
      football: "#",
      "sandals and slides": "#",
    },
    "girls shoes": {
      "all shoes": "#",
      "older girls (7 - 14 years)": "#",
      "younger girls (4 - 7 years)": "#",
      "babies and toddlers (0 - 4 years)": "#",
      lifestyle: "#",
      jordan: "#",
      running: "#",
      basketball: "#",
      football: "#",
      "sandals and slides": "#",
    },
    "boys clothing": {
      "tops and t-shirts": "#",
      "hoodies and sweatshirts": "#",
      "pants and leggings": "#",
      shorts: "#",
      "all boys clothing": "#",
    },
    "girls clothing": {
      "tops and t-shirts": "#",
      "sports bras": "#",
      "hoodies and sweatshirts": "#",
      "pants and leggings": "#",
      shorts: "#",
      "all girls clothing": "#",
    },
    "accessories and equipment": {
      "all accessories and equipment": "#",
      "bags and backpacks": "#",
      socks: "#",
      "hats and headwear": "#",
    },
    "shop by sport": {
      football: "#",
      running: "#",
      basketball: "#",
      "gym and training": "#",
      tennis: "#",
    },
  },

  customize: "#",
  SNKRS: "#",
};
